---
title: "Webscraping homework"
author: "Emil Jacobsen"
date: "2022-11-07"
output:
	html_document:
	toc: true
  toc_float: true
  toc_collapsed: true
  toc_depth: 3
  number_sections: true
  theme: lumen
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
library(rvest)
library(dplyr)
library(tidyr)
library(stringr)
library(janitor)
library(tidyverse)
library(lubridate)

```


```{r url}
url <- "https://www.worldometers.info/world-population/population-by-country/"
# scrape the website
url_html <- read_html(url)
```

```{r scrape-table}
whole_table <- url_html %>% 
 html_nodes("table") %>%
 html_table()  #str(whole_table) turns out to be a list
str(whole_table)
whole_table[[1]]
whole_table
```


```{r html-to-df}
new_table <- do.call(cbind,unlist(whole_table, recursive = FALSE)) 
head(new_table)
```

```{r write-to-csv}
write.csv(whole_table,"Data_Worldpop.csv")
World_pop_csv<- read.csv("./Data_Worldpop.csv")

```

```{r Changing col names}
#Changing needed collumn names in the csv becuase the naming suuuuucks
	names(World_pop_csv)[names(World_pop_csv) == "Country..or.dependency."] <- "Country_or_Dependency"
  names(World_pop_csv)[names(World_pop_csv) == "Population..2020."] <- "Population_2020"
World_pop_csv
```

```{r making bar plot}
#making bar plot to map population differences, for some reason it makes India and china very low? no idea why
World_pop_csv %>% 
	top_n(10) %>% 
	ggplot(aes(x = Country_or_Dependency, y = Population_2020)) +
           geom_col(alpha = 1) +
           labs(title = "Population_2020",
                x = "Country",
                y = "Population") +
           theme_bw()

```
That turned out pretty bad, but i am proud of myself nonetheless

```{r Facets}
#faceting the countries for some reason
World_pop_csv %>% 
	top_n(3) %>% # for some reason it won't aknowledge China and india? i suspect it might be because i didnt clean the collumns properly or because their populations are above 1 billion
  ggplot(aes(x = Country_or_Dependency , y = Population_2020)) +
  geom_col(alpha = 1) +
  facet_wrap(facets = vars(Country_or_Dependency)) +
  labs(title = "Population Data",
       x = "Country",
       y = "Population") +
  theme_bw()


```


