---
title: "Examproject"
author: "Emil Brutnse Jacobsen"
date: "2023-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r installing and enabling packages, include=FALSE}
#install.packages("tidyverse")
#install.packages("here")
#install.packages("ggridges")
#unhastag the above if not installed


library(tidyverse)
library(here)
library(data.table)
library(rvest)
library(dplyr)
library(tidyr)
library(stringr)
library(janitor)
library(ggplot2)
library(ggridges)
```

Importing the data
```{r getting csv}
#reading the csv file and making it into an object
Raw_data <- read.csv("data/base-datos_Mulig.csv")

```

Cleaning and translating data
```{r cleaning}
#translating all collumn names to english

setnames(Raw_data, old = c('Nome','Apelidos','Apodo','Suceso','Sexo','Idade','Profesión','Natural.Concello','Natural.Comarca','Natural.Provincia','Lugar','Veciño.Concello','Veciño.Comarca','Veciño.Provincia','Morte','Traxectoria'), 
         new = c('name','surname','nicknames','event','gender','age','profession','council','municipality','province','place','neighbor_council','neighbor_municipality','neighbor_province','death','trajectory'))

#filling 0000-00-00 date spaces with NA
Raw_data[Raw_data == '0000-00-00'] <- NA
#translating data set when nessecary
Raw_data[Raw_data == 'Home'] <- "Male"
Raw_data[Raw_data == 'Muller'] <- "Female"
Raw_data[Raw_data == 'Morte (outras tipoloxías)'] <- "Other causes"
Raw_data[Raw_data == 'Proceso'] <- "Lawsuit"
Raw_data[Raw_data == 'Prisión'] <- "Prison"
Raw_data[Raw_data == 'Paseo'] <- "Firing Squad"
Raw_data[Raw_data == 'Outras tipoloxías represivas'] <- "Other causes"
Raw_data[Raw_data == 'Execución fóra de Galicia'] <- "Executed outside of Galicia"
Raw_data[Raw_data == 'Execución'] <- "Execution"
Raw_data[Raw_data == 'Detención'] <- "Detention"
Raw_data[Raw_data == 'Desaparición'] <- "Dissapeared"
Raw_data[Raw_data == 'Causa militar-execución'] <- "Military execution"
Raw_data[Raw_data == 'Campo de Exterminio'] <- "Death camp"
Raw_data[Raw_data == 'Descoñecido'] <- "Unknown"


#dropping rows with NA
deaths <- na.omit(Raw_data)
#making string to make new column
years_only <- substring(deaths$death, 1, nchar(deaths$death)-6)
#making new column with year of death only
deaths["year"] <- years_only    
```

```{r Barplot for all victims}
Raw_data %>% 
  #making ggplot
  ggplot(aes(y = event,
             )) +
  geom_bar(size = 0.5) +
  labs(title = "Victims from 1936-1945 by method",
      x = "Number of people",
      y = "Method of Repression") +
theme_bw()

  
```


```{r Deaths from 1936-1945}
deaths %>% 
  ggplot(aes(x = year,
             )) +
  geom_bar(size = 0.5) +
  labs(title = "Deaths from 1936-1945",
      x = "Year",
      y = "Number of people") +
theme_bw()

 
```
```{r Methods of lethal repression}
deaths %>% 
  ggplot(aes(y = event,
             )) +
  geom_bar(size = 0.5) +
  labs(title = "Deaths from 1936-1945 by method",
      x = "Number of people",
      y = "Method of repression") +
theme_bw()

 
```


```{r Deaths from 1936-1942 sorted by Municipality}
#same ggplot as before but faceted and without years
deaths %>%
  #filtering out rows missing provinces
  filter(province %in% c("A Coruña", "Descoñecida", "Lugo","Ourense","Pontevedra")) %>% 
  ggplot(aes(x = year
             )) +
  geom_bar(size = 0.5) +
  labs(title = "Deaths from 1936-1942 sorted by Province",
      x = "Year",
      y = "Number of people") +
  #making it show provinces separately
  facet_wrap(~province) +
  #removing x labels as they were cluttered
theme(axis.text.x=element_blank())

 
```

```{r age of victims}
#Age distribution of lethal victims
deaths %>% 
  filter(gender %in% c("Male", "Female")) %>% 
  ggplot(aes(x = age,
             y = factor(year),
             fill = gender)) +
  geom_density_ridges(alpha = 0.5, 
                      scale = 0.9)  +
  theme_ridges(font_size = 10) +
  scale_x_continuous(breaks = seq(0, 100, 10),
                     labels = seq(0, 100, 10)) +
  xlab("Age at death (years)") +
  ylab("Year") +
  theme(axis.title = element_text(size = 14))
```


```{r Method of repression through 1936-1945}
deaths %>% 
  ggplot(aes(y = event,
             x = year)) +
  #changed the type og ggplot
  geom_bin2d(size = 0.5) +
  labs(title = "Method of repression through 1936-1950",
      x = "Years",
      y = "Method of repression") +
theme_bw()

 
 
```


